spring.application.name=Examplereact-1
spring.datasource.url=jdbc:postgresql://dpg-d7kabhvlk1mc738teht0-a:5432/examplereact_db
spring.datasource.username=examplereact_db_user
spring.datasource.password=8EWdQQZ1b3uqQWK2YMOdK4HCxgHSqr8C

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ssivamyadav0123@gmail.com
spring.mail.password=zyla qwwz rlrt nbri
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
